version: '3.7'

services:

  # postgreSQL service (share data between services)

  postgres_dwh:
    image: postgres:10-alpine
    container_name: postgres_dwh
    volumes:
    
      # - "./data_repo:/host"
      # - ./scripts:/docker-entrypoint-initdb.d
      - ./backup:/backup
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: $DWH_POSTGRES_ADMIN
      POSTGRES_PASSWORD: $DWH_POSTGRES_PASSWORD
      POSTGRES_DB: $DWH_POSTGRES_DATABASE
  dbt:
    image: datafuel/dbt
    # build: ./dbt_repo
    # command: python -u metabase_setup.py
    container_name: dbt
    expose:
      - 4444
    ports:
      - 4444:4444
    volumes:
      - ./dbt_repo/src:/src
      - ./dbt_repo/profiles:/root/.dbt
      - ./dbt_repo/metabt:/src_metabt/metabt
    environment:
      DWH_POSTGRES_ADMIN: $DWH_POSTGRES_ADMIN
      DWH_POSTGRES_PASSWORD: $DWH_POSTGRES_PASSWORD
      DWH_POSTGRES_DB: $DWH_POSTGRES_DATABASE
      DWH_POSTGRES_HOST: postgres_dwh
      MB_ADMIN_EMAIL: $MB_ADMIN_EMAIL
      MB_ADMIN_PASSWORD: $MB_ADMIN_PASSWORD
      DWH_POSTGRES_PORT: 5432
      DWH_POSTGRES_STG_SCHEMA: stg
      DWH_POSTGRES_PRS_SCHEMA: prs
      MB_ADMIN_FIRST_NAME: $MB_ADMIN_FIRST_NAME
      MB_ADMIN_LAST_NAME: $MB_ADMIN_LAST_NAME
    stdin_open: true
    tty: true

networks: 
    default: 
        external: 
            name: datafuel-local-network

